using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Lib.GAB.Generators
{
    [Generator(LanguageNames.CSharp)]
    public sealed class ToolResponseSchemaGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Find all methods with [Tool] attribute
            var toolMethods = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AnonymousTypeAnalyzer.ToolAttributeFullName,
                    predicate: static (node, _) => node is MethodDeclarationSyntax,
                    transform: static (ctx, _) =>
                    {
                        var method = (MethodDeclarationSyntax) ctx.TargetNode;
                        return AnonymousTypeAnalyzer.Analyze(method, ctx.SemanticModel);
                    });

            // Collect all schemas and generate output
            var collected = toolMethods.Collect();

            context.RegisterSourceOutput(collected, static (spc, schemas) =>
            {
                // Report diagnostics
                foreach (var schema in schemas)
                {
                    foreach (var diag in schema.Diagnostics)
                    {
                        spc.ReportDiagnostic(diag.ToDiagnostic());
                    }
                }

                // Group schemas by class (namespace + class name)
                // Include ALL tool methods so partial declarations are emitted for each
                var byClass = schemas
                    .Where(s => !string.IsNullOrEmpty(s.ClassName))
                    .GroupBy(s => (s.Namespace, s.ClassName));

                foreach (var group in byClass)
                {
                    var source = GeneratePartialClass(group.Key.Namespace, group.Key.ClassName, group.ToList());
                    var fileName = string.IsNullOrEmpty(group.Key.Namespace)
                        ? $"{group.Key.ClassName}.g.cs"
                        : $"{group.Key.Namespace}.{group.Key.ClassName}.g.cs";
                    spc.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
                }
            });
        }

        private static string GeneratePartialClass(
            string ns,
            string className,
            List<AnonymousTypeAnalyzer.ToolSchema> methods)
        {
            var sb = new StringBuilder();

            // Collect additional using directives from all methods in this class
            var extraUsings = new HashSet<string>();
            foreach (var m in methods)
            {
                foreach (var ns2 in m.UsingNamespaces)
                    extraUsings.Add(ns2);
            }

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Lib.GAB.Tools;");
            // Remove namespaces already emitted unconditionally above
            extraUsings.Remove("System.Threading.Tasks");
            extraUsings.Remove("Lib.GAB.Tools");

            foreach (var extra in extraUsings.OrderBy(u => u))
            {
                sb.AppendLine($"using {extra};");
            }
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.AppendLine($"{indent}partial class {className}");
            sb.AppendLine($"{indent}{{");

            foreach (var method in methods)
            {
                if (string.IsNullOrEmpty(method.MethodName))
                    continue;

                // Emit [ToolResponse] attributes if we have a valid schema
                if (method.Fields != null && method.Fields.Count > 0)
                {
                    EmitFieldAttributes(sb, method.Fields, indent + "    ", "");
                }

                // Emit partial method declaration (no body) for all [Tool] methods
                sb.AppendLine($"{indent}    {method.Modifiers} partial {method.ReturnType} {method.MethodName}{method.Parameters};");
                sb.AppendLine();
            }

            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void EmitFieldAttributes(
            StringBuilder sb,
            List<AnonymousTypeAnalyzer.FieldSchema> fields,
            string indent,
            string prefix)
        {
            foreach (var field in fields)
            {
                var fullName = string.IsNullOrEmpty(prefix) ? field.Name : $"{prefix}.{field.Name}";
                var attrs = new List<string>();
                attrs.Add($"\"{EscapeString(fullName)}\"");
                attrs.Add($"Type = \"{field.JsonType}\"");
                if (field.Description != null)
                    attrs.Add($"Description = \"{EscapeString(field.Description)}\"");
                if (field.Nullable)
                    attrs.Add("Nullable = true");

                sb.AppendLine($"{indent}[ToolResponse({string.Join(", ", attrs)})]");

                // Recurse for nested items
                if (field.Items != null && field.Items.Count > 0)
                {
                    EmitFieldAttributes(sb, field.Items, indent, fullName);
                }
            }
        }

        private static string EscapeString(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r")
                .Replace("\t", "\\t")
                .Replace("\0", "\\0");
        }
    }
}